
# source files
src:
  js:
    - ./src/app/index.jsx
  css:
    - ./src/app/styles/main.styl
  stat:
    - ./static/**/*

# files to watch for changes in
watch:
  js:
    - ./src/**/*.+(js|jsx|hbs)
  css:
    - ./src/app/styles/**/*.+(styl|css)

  stat:
    - ./static/**/*

# destination folders
dest:
  js:   ./public
  css:  ./public
  stat: ./public/static
